-- =============================================================
-- Tesla Brand Sentiment Tracker
-- Initial PostgreSQL Load Script
-- Developer: Michael Chen
-- =============================================================

-- Drop schema if exists for clean reload
DROP SCHEMA IF EXISTS tesla_sentiment CASCADE;
CREATE SCHEMA tesla_sentiment;
SET search_path TO tesla_sentiment;

-- =============================================================
-- TABLE: subreddits
-- Lookup table for tracked Reddit communities
-- =============================================================
CREATE TABLE subreddits (
    subreddit_id    SERIAL PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL UNIQUE,
    display_name    VARCHAR(150),
    description     TEXT,
    subscriber_count INT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- =============================================================
-- TABLE: posts
-- Raw Reddit posts collected via PRAW
-- =============================================================
CREATE TABLE posts (
    post_id         VARCHAR(20)     PRIMARY KEY,   -- Reddit's native post ID (e.g. 't3_abc123')
    subreddit_id    INT             NOT NULL REFERENCES subreddits(subreddit_id),
    title           TEXT            NOT NULL,
    body            TEXT,
    author          VARCHAR(100),
    score           INT             NOT NULL DEFAULT 0,
    upvote_ratio    NUMERIC(4,3),                  -- e.g. 0.923
    num_comments    INT             NOT NULL DEFAULT 0,
    url             TEXT,
    is_self_post    BOOLEAN         NOT NULL DEFAULT TRUE,
    collected_at    TIMESTAMP       NOT NULL DEFAULT NOW(),
    posted_at       TIMESTAMP       NOT NULL
);

-- =============================================================
-- TABLE: comments
-- Individual comments tied to a post
-- =============================================================
CREATE TABLE comments (
    comment_id      VARCHAR(20)     PRIMARY KEY,   -- Reddit's native comment ID
    post_id         VARCHAR(20)     NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
    parent_id       VARCHAR(20),                   -- NULL if top-level comment; comment_id of parent if reply
    author          VARCHAR(100),
    body            TEXT            NOT NULL,
    score           INT             NOT NULL DEFAULT 0,
    depth           SMALLINT        NOT NULL DEFAULT 0,
    collected_at    TIMESTAMP       NOT NULL DEFAULT NOW(),
    posted_at       TIMESTAMP       NOT NULL
);

-- =============================================================
-- TABLE: sentiment_scores
-- VADER + TextBlob scores for posts and comments
-- Decoupled from raw data so model can be re-run without data loss
-- =============================================================
CREATE TABLE sentiment_scores (
    score_id        SERIAL          PRIMARY KEY,
    target_id       VARCHAR(20)     NOT NULL,       -- post_id or comment_id
    target_type     VARCHAR(10)     NOT NULL CHECK (target_type IN ('post', 'comment')),
    model           VARCHAR(20)     NOT NULL CHECK (model IN ('vader', 'textblob')),
    compound        NUMERIC(5,4),                   -- VADER: -1.0 to 1.0
    positive        NUMERIC(5,4),                   -- VADER positive component
    negative        NUMERIC(5,4),                   -- VADER negative component
    neutral         NUMERIC(5,4),                   -- VADER neutral component
    polarity        NUMERIC(5,4),                   -- TextBlob: -1.0 to 1.0
    subjectivity    NUMERIC(5,4),                   -- TextBlob: 0.0 to 1.0
    sentiment_label VARCHAR(10)     NOT NULL CHECK (sentiment_label IN ('positive', 'neutral', 'negative')),
    scored_at       TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (target_id, target_type, model)
);

-- =============================================================
-- TABLE: topics
-- LDA topic labels generated by Gensim
-- =============================================================
CREATE TABLE topics (
    topic_id        SERIAL          PRIMARY KEY,
    topic_label     VARCHAR(100)    NOT NULL,       -- Human-readable label e.g. 'Autopilot & Software'
    keywords        TEXT[]          NOT NULL,       -- Top keywords from LDA e.g. ARRAY['autopilot','fsd','crash']
    model_version   VARCHAR(20),                    -- Track which LDA model run produced this topic
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- =============================================================
-- TABLE: post_topics
-- Junction table: many-to-many between posts and topics
-- Includes weight score from LDA (how strongly a post maps to a topic)
-- =============================================================
CREATE TABLE post_topics (
    post_id         VARCHAR(20)     NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
    topic_id        INT             NOT NULL REFERENCES topics(topic_id) ON DELETE CASCADE,
    weight          NUMERIC(5,4)    NOT NULL,       -- LDA probability weight: 0.0 to 1.0
    PRIMARY KEY (post_id, topic_id)
);

-- =============================================================
-- TABLE: tesla_events
-- Manually curated timeline of major Tesla events
-- Used as overlay layer on sentiment time-series charts
-- =============================================================
CREATE TABLE tesla_events (
    event_id        SERIAL          PRIMARY KEY,
    event_date      DATE            NOT NULL,
    event_type      VARCHAR(50)     NOT NULL CHECK (event_type IN (
                        'product_launch',
                        'recall',
                        'earnings',
                        'executive_news',
                        'regulatory',
                        'pr_incident',
                        'competition',
                        'other'
                    )),
    title           VARCHAR(255)    NOT NULL,
    description     TEXT,
    source_url      TEXT,
    sentiment_impact VARCHAR(10)    CHECK (sentiment_impact IN ('positive', 'negative', 'neutral', 'mixed')),
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- =============================================================
-- INDEXES
-- =============================================================

-- Posts: filter by subreddit and date range frequently
CREATE INDEX idx_posts_subreddit      ON posts(subreddit_id);
CREATE INDEX idx_posts_posted_at      ON posts(posted_at);
CREATE INDEX idx_posts_score          ON posts(score DESC);

-- Comments: look up by post and date
CREATE INDEX idx_comments_post_id     ON comments(post_id);
CREATE INDEX idx_comments_posted_at   ON comments(posted_at);

-- Sentiment: look up by target and model
CREATE INDEX idx_sentiment_target     ON sentiment_scores(target_id, target_type);
CREATE INDEX idx_sentiment_label      ON sentiment_scores(sentiment_label);
CREATE INDEX idx_sentiment_scored_at  ON sentiment_scores(scored_at);

-- Tesla events: filter by date and type for dashboard overlays
CREATE INDEX idx_events_date          ON tesla_events(event_date);
CREATE INDEX idx_events_type          ON tesla_events(event_type);

-- =============================================================
-- SEED DATA: subreddits
-- =============================================================
INSERT INTO subreddits (name, display_name, description, is_active) VALUES
    ('Tesla',             'r/Tesla',             'Main Tesla community',                         TRUE),
    ('teslamotors',       'r/teslamotors',        'Tesla Motors enthusiasts',                     TRUE),
    ('electricvehicles',  'r/electricvehicles',   'Broader EV discussion including Tesla',        TRUE),
    ('stocks',            'r/stocks',             'Stock market discussion — Tesla ticker TSLA',  TRUE);

-- =============================================================
-- SEED DATA: tesla_events (sample events for initial load)
-- =============================================================
INSERT INTO tesla_events (event_date, event_type, title, description, sentiment_impact) VALUES
    ('2024-01-24', 'earnings',        'Q4 2023 Earnings Miss',            'Tesla misses revenue estimates; stock drops 12%',                                  'negative'),
    ('2024-03-01', 'product_launch',  'Refreshed Model 3 US Launch',      'Updated Model 3 Highland begins US deliveries',                                    'positive'),
    ('2024-04-23', 'earnings',        'Q1 2024 Earnings — Revenue Miss',  'Revenue declines YoY; price cuts cited; Musk announces cheaper model',            'mixed'),
    ('2024-06-13', 'executive_news',  'Musk Pay Package Approved',        'Shareholders approve $56B Elon Musk compensation package',                         'mixed'),
    ('2024-07-23', 'earnings',        'Q2 2024 Earnings Beat',            'Tesla beats estimates; energy business growth highlighted',                        'positive'),
    ('2024-10-10', 'product_launch',  'Robotaxi / Cybercab Reveal',       'Tesla unveils Cybercab autonomous vehicle at We, Robot event',                    'mixed'),
    ('2024-10-23', 'earnings',        'Q3 2024 Earnings Beat',            'Strong margins recovery; stock surges after-hours',                                'positive'),
    ('2024-11-01', 'recall',          'Cybertruck Recall — Trim Panel',   'NHTSA recall of 2,431 Cybertrucks for exterior trim panel detachment risk',        'negative'),
    ('2025-01-29', 'earnings',        'Q4 2024 Earnings Miss',            'Revenue and deliveries below expectations; guidance concerns',                     'negative'),
    ('2025-03-15', 'pr_incident',     'Musk DOGE Role — Brand Backlash',  'Protests at Tesla dealerships amid Musk government role controversy',              'negative');

-- =============================================================
-- SEED DATA: topics (sample LDA topic stubs)
-- =============================================================
INSERT INTO topics (topic_label, keywords, model_version) VALUES
    ('Autopilot & FSD',         ARRAY['autopilot','fsd','crash','self-driving','camera','beta'],        'lda_v1'),
    ('Pricing & Affordability', ARRAY['price','cut','affordable','cost','discount','msrp'],             'lda_v1'),
    ('Vehicle Quality',         ARRAY['build','quality','panel','gap','paint','defect','service'],      'lda_v1'),
    ('Elon Musk & Leadership',  ARRAY['elon','musk','ceo','tweet','doge','leadership','politics'],      'lda_v1'),
    ('Competition & EV Market', ARRAY['rivian','lucid','ev','byd','ford','gm','market','share'],        'lda_v1'),
    ('Stock & Financials',      ARRAY['tsla','stock','earnings','revenue','margin','invest','short'],   'lda_v1');

-- =============================================================
-- VERIFICATION QUERIES
-- Run after load to confirm seed data inserted correctly
-- =============================================================
SELECT 'subreddits'   AS table_name, COUNT(*) AS row_count FROM subreddits
UNION ALL
SELECT 'tesla_events' AS table_name, COUNT(*) AS row_count FROM tesla_events
UNION ALL
SELECT 'topics'       AS table_name, COUNT(*) AS row_count FROM topics;
